__author__ = 'alexkane'

import lab17
import unittest


class TestKruskal(unittest.TestCase):
    def test_trivial(self):
        graph = lab17.WeightedGraph()
        graph.add_vertex(0)
        graph.add_vertex(1)
        graph.add_vertex(2)
        graph.add_vertex(3)
        graph.add_vertex(4)
        graph.add_directed_link(0, 1, 3)
        graph.add_directed_link(0, 2, 1)
        graph.add_directed_link(2, 1, 1)
        graph.add_directed_link(0, 3, 6)
        graph.add_directed_link(2, 4, 2)
        graph.add_directed_link(4, 3, 1)
        graph.add_directed_link(3, 2, 1)
        graph.add_directed_link(4, 1, 3)
        res = graph.min_tree()
        self.assertEqual(res.graph[0].ribs[0].source, 0)
        self.assertEqual(res.graph[0].ribs[0].destination, 2)
        self.assertEqual(res.graph[0].ribs[0].weight, 1)
        self.assertEqual(res.graph[1].ribs[0].source, 1)
        self.assertEqual(res.graph[1].ribs[0].destination, 2)
        self.assertEqual(res.graph[1].ribs[0].weight, 1)
        self.assertEqual(res.graph[2].ribs[0].source, 2)
        self.assertEqual(res.graph[2].ribs[0].destination, 0)
        self.assertEqual(res.graph[2].ribs[0].weight, 1)
        self.assertEqual(res.graph[2].ribs[1].source, 2)
        self.assertEqual(res.graph[2].ribs[1].destination, 1)
        self.assertEqual(res.graph[2].ribs[1].weight, 1)
        self.assertEqual(res.graph[2].ribs[2].source, 2)
        self.assertEqual(res.graph[2].ribs[2].destination, 3)
        self.assertEqual(res.graph[2].ribs[2].weight, 1)
        self.assertEqual(res.graph[3].ribs[0].source, 3)
        self.assertEqual(res.graph[3].ribs[0].destination, 2)
        self.assertEqual(res.graph[3].ribs[0].weight, 1)
        self.assertEqual(res.graph[3].ribs[1].source, 3)
        self.assertEqual(res.graph[3].ribs[1].destination, 4)
        self.assertEqual(res.graph[3].ribs[1].weight, 1)
        self.assertEqual(res.graph[4].ribs[0].source, 4)
        self.assertEqual(res.graph[4].ribs[0].destination, 3)
        self.assertEqual(res.graph[4].ribs[0].weight, 1)
